### ISSUE TITLE
Go odbc drill not work

### ISSUE THREAD

**Issue by sundy-li** [ctownsen357/drill-odbc#1]
Hi, please see https://github.com/alexbrainman/odbc/issues/68, I faced this problem ~

**Comment by ctownsen357** [comment]
Sundy, I haven't used zookeeper yet.  I've only used drill embedded thus far and am able to specify a host and port.  Currently, I've been able to connect via this ODBC driver but need to do some conversion of the query string type as the Unicode string isn't working once it reaches my embedded drill server.

Not being able to specify a host and port for zookeeper is likely going to be a problem since the ODBC software won't be able to connect to anything.
